services:
  - type: web
    name: flowbit-vanna-ai
    env: python
    plan: free
    rootDir: apps/vanna
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 10000

